from Volunteer.models import Team
TEAMS = ['ada': 5,
        'center_camp': 5,
        'city_planning': 12,
        'commissary': 35,
        'dispatch': ,
        'dispensary': 8,
        'fire': 13,
        'gate': 32,
        'greeters': 10,
        'lnt': 23,
        'outreach': 11,
        'paparaunchy': 5,
        'playshops': 11,
        'please': 38,
        'road_warriors': 44,
        'sales': 5,
        'swag': 5,
        'teleportus ': 38,
        'ticketing ': 16,
        'waldos': 40,
        'wolf_pack':22,
        ]  
TEAM_DESCRIPTION_DICT = {
                      'ada': "Mobility Assistance",
                      'art_curation': "Coordinating with local artists to keep YOUtopia weird.",
                      'city_planning': "Whether it's managing the stage and myriad activities at Center Camp or maintaining sacred space at the Temple, this crew helps maintain spaces where each and every YOUtopian can gift their participation.",
                      'center_camp': "Whether it’s managing the stage and myriad activities at Center Camp or maintaining sacred space at the Temple, this crew helps maintain spaces where each and every YOUtopian can gift their participation.",
                      'commissary' : "So you're hungry, are you? The good people at the Commissary make sure the event crew can stay fat and sassy by keeping them fed, because we all love to keep it sassy.",
                      'dispatch' : "Dispatch are the masters of radio communication. They keep our airwaves clear and help distribute information. Over.",
                      'dispensary' : "I got what you want. I got what you need. The dispensary maintains YOUtopia supplies and equipment and makes sure each department is set up for success.",
                      'fire' : "Keeping us safe from lighting ourselves, others, and anything other than approved art and performance on fire, Fire Safety knows to keep the fire alive at the event. They’re also the hard working crew that facilitates safety classes at the event to give you your first opportunity (or perhaps your 7,456,398 opportunity) to light up your fire.",
                      'gate' : "These are the people who make sure your entrance into the event is a smooth ride. They check that you know about the rules concerning what you can bring into the event (No Glass or Firewood please!), make sure you have your ticket, and work closely with Security to protect the perimeter of the event.",
                      'greeters' : "These are the folks that welcome participants with open arms into YOUtopia, while making sure you know where you’re going, providing answers to your questions about the event, and giving you a good hug (or a good spanking) at your request. ",
                      'lnt' : "The Moopgician crew makes sure that participants leave a pristine location when the event is over. They help educate participants on having the least ecological impact and “Pack It In, Pack It Out” principles. They may also sometimes be found leading scavenger hunts and games.",
                      'outreach' : "Masters of media relations and information dissemination, the OUTreach team knows what's shakin' and keeps the party rockin'.",
                      'paparaunchy' : "If there's a totally righteous party in the forest, and no one is there to see it, did it really happen? Our media crew documents building the city from the early planning meetings to cleaning up on the way out.",
                      'playshops' : "Aptly titled because they’re all about play!, Playshops provide activities like that early sunrise yoga to get a jumpstart to your day, a lesson on how to plant your very own unicorn, or a open dialogue about what it means to be a burner. Playshops & Performances Support play cupid, matchmaking Theme Camps with open space to host with those seeking a space to express their creativity. As wide-ranging as the imagination, they sometimes need a little support with those yoga mats or unicorn seeds.",
                      'please' : "The Please Department supports the service of all other YOUtopia volunteer crews. They’re an elite strike force whose mission is to ensure members of the event team take care of themselves by delivering food, snacks, extra help, and overall fun. When not caretaking for other departments, they can usually be found instigating shenanigans somewhere in the event.",
                      'road_warriors' : "The Road Warriors make sure we can all fit comfortably in the event. Working closely with City Planning, Road Warriors have a good handle on mapping out how exactly to fit all the cars, RVs, and other vehicles into the event with style and grace. They're looking for experienced volunteers who work hard and play hard.",
                      'sales' : "Slinging coffee and ice on the mountain, the Sales crew wakes us up and keeps things cool, and donates the proceeds to the tribe.",
                      'swag' : "Make 2015 memorable for all our volunteers with awesome gear and nifty collectibles.",
                      'teleportus' : "Facilitating shuttles and art cars to help cruise participants around YOUtopia in style, TeleportUs crew keeps it movin.",
                      'ticketing' : "They're making a list and checking it twice. These volunteers keep the line cruising.",
                      'waldos' : "The Waldos keep an eagle eye open for uninvited guestss. They maintain a drag net to keep the perimeter secure and work closely with security to ensure anyone who isn't supposed to be at the event isn't at the event.",  
                      'wolf_pack' : "Abiding by their motto, \"First To Come, Last To Pull Out,\" the Wolf Pack are a die hard crew. Literally building the event from the ground up, this crew sees to it that the infrastructure for our fair YOUtopian city is in place for the event. They are also responsible for disassembling everything at the conclusion of the event so our city leaves no trace.",
                      'ass' : "Some teams will be choosing the most dedicated, experienced volunteers to train as assistants to the leads. These super volunteers will receive more training and more responsibility. Not everyone is cut out for this position, but we're looking for the best of the best.",
                      'team' : "Some department heads are recruiting team members in advance. If you haven't already been recruited, not to fret! We will help place you on a team that fits your skills and interests.",
                      }
                      
for team_name, budget in teams:
    team = Team(budget= budget, name= team_name, description = TEAM_DESCRIPTION_DICT[team_name])
    team.save
    
    